services:
  - type: web
    name: quick-news-bot
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: IG_USERNAME
        sync: false
      - key: IG_PASSWORD
        sync: false
      - key: NEWS_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.9.18
    healthCheckPath: /health
    numInstances: 1
    buildCommand: docker build -t quick-news-bot .
