services:
  - type: worker
    name: quicknews-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python scheduler.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
